### ISSUE TITLE
Error building docker

### ISSUE THREAD

**Issue by HoxhaEndri** [binareio/FastCVE#2]
Repository fresh cloned, I try to build the container with `sudo docker-compose build`, but I receive this error:
`$ sudo docker-compose build`

`WARNING: The ENV_POSTGRES_CONF variable is not set. Defaulting to a blank string.
WARNING: The PWD variable is not set. Defaulting to a blank string.
Building fastcve
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Dockerfile: no such file or directory
ERROR: Service 'fastcve' failed to build : Build failed
`
Can you please help me?

**Comment by binareio** [comment]
Don't use `sudo`, try to build just with `docker-compose build`. If you get rights error when running without the `sudo`, consider adding your account to the docker group.

**Comment by HoxhaEndri** [comment]
Thank you, adding my user to the docker group did solve the problem.
